old = open("source_leetcode_data.txt")
new = open("intervals.md", "a")
new.write('# Intervals\n\n')
head = old.readline(0)
lower_head = head.lower()
split_head = head.split(' ')
new.write('+[' + head + ']' + '(#' + split_head[0] + '-' + split_head[1] + ')\n\n')

new.write('##' + head + '\n\n')
link = old.readline(1)
new.write(link + '\n\n')
full_text = str(old.readlines)
body = full_text.split('    ', 2)
new.write('```python\n' + body[1] + '\n' + '```')
new.write(body[1])
