old = open(r"C:\Users\User\Desktop\python\source_leetcode_data.txt")
new = open(r"C:\Users\User\Desktop\python\intervals.md", "a")
new.write('\n# Intervals\n\n')
head = old.readline()
head = head.replace('\n', '')
lower_head = head.lower()
split_head = lower_head.split(' ')
if split_head[2] != '':
    new.write('+[' + head + ']' + '(#' + split_head[0] + '-' + split_head[1] + '-' + split_head[2] + ')\n\n')
else:
    new.write('+[' + head + ']' + '(#' + split_head[0] + '-' + split_head[1] + ')\n\n')
new.write('##' + head + '\n\n')
link = old.readline()
link = link.replace('\n', '')
new.write(link + '\n\n')
full_text = old.read()
index_def = full_text.find('def')
body = full_text[index_def-1:-1]
new.write('```python\n' + body + '\n' + '```')
old.close()
new.close()
